# Generated by Django 4.2.7 on 2023-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('passHash', models.CharField(max_length=150)),
                ('passSalt', models.CharField(max_length=150)),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
    ]