# Generated by Django 4.2.7 on 2023-12-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gndn', '0002_loginstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogInStatus',
        ),
    ]
