# Generated by Django 4.2.7 on 2023-12-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gndn', '0003_delete_loginstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyValue', models.CharField(max_length=9)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
